config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [] do
    collection do
      get :search
      post :find
      post :export
      post :exclude
    end
  end

  resources :data, only: [:index] do
    collection do
      post :join
    end
  end
  resources :batches, only: [:index, :show]
  resources :payments, only: [] do
    collection do
      get :upload
      post :transfer
      get "/:batch_id/columns" => "payments#column", as: "columns"
      post "/:batch_id/process" => "payments#process_batch", as: "process"
    end
  end
  resources :infringements, only: [:show] do
    collection do
      get :upload
      post :transfer
      get "/:batch_id/columns" => "infringements#column", as: "columns"
      post "/:batch_id/process" => "infringements#process_batch", as: "process"
    end
  end

end

app/models/infringement.rb
class Infringement < ActiveRecord::Base

  before_create :set_o_infringement_type

  validates :code, uniqueness: true

  def set_o_infringement_type
    self.o_infringement_type = self.infringement_type
  end

end

app/controllers/infringements_controller.rb
class InfringementsController < ImporterController

  before_action :set_batch, only: [:column, :process_batch]
  before_action :check_for_csv, only: [:transfer]
  before_action :file_name, only: [:transfer]

  def show
    @infringement = Infringement.find(params[:id])
  end

  # GET
  def upload
  end

  # POST
  # (Subir archivos) direcciona a listar columnas
  def transfer
    # Crear un batch process, de tipo payment
    @batch = Batch.create(import_type: "infringement", import_running: false, status: "pending", file_name: @file_name)
    # Recibir el archivo enviado y guardar en las rutas
    process_transfer "#{@batch.id}_c", "#{@batch.id}_d", columns_infringements_path(@batch)
  end

  # GET
  # Leer la columna del archivo a importar
  def column
    @columns = read_column "#{@batch.id}_c"
  end

  # POST
  # Realizar el proceso de importación de pagos
  # TODO: Realizae este proceso en un delayed job
  def process_batch
    InfringementsController.delay.process_batch_delayed(@batch, params)
    return redirect_to @batch, notice: "La importación de comparendos se está procesando."
  end

  private

  def self.process_batch_delayed batch, params
    # Parámetros requerido (Columna)
    _p = params.require(:csv).permit(:infringement_type, :infringement_number, :infringement_date)
    infringement_type = _p[:infringement_type]
    infringement_number = _p[:infringement_number].to_i
    infringement_date = _p[:infringement_date].to_i
    # Recorrer datos
    traverse_data(batch) do |row|
      date = ""; code = "";
      code = row[infringement_number].strip unless row[infringement_number].nil?
      date = row[infringement_date].strip unless row[infringement_date].nil?
      if code != "" && date != ""
        parsed_date = Chronic.parse(date)
        unless parsed_date.nil?
          infringement = Infringement.new(code: code, infringement_type: infringement_type, date: parsed_date)
          if infringement.save
            @imported = @imported + 1
          else
            if parsed_date >= infringement.date
              infringement.update_attributes date: row[infringement_date], infringement_type: infringement_type
            end
            @failed = @failed + 1
          end
        else
          @failed = @failed + 1
        end
      else
        @failed = @failed + 1
      end
      @total = @total + 1
      batch.update_attributes(total: @total, failed: @failed, imported: @imported)
    end
  end

  def set_batch
    @batch = Batch.find(params[:batch_id])
  end

end

app/views/infringements/column.html.erb
<div class="ui attached message">
  <div class="header">
    Importar: <%= @batch.file_name %>
  </div>
  <p>Elija la columna que desea importar, teniendo en cuenta que será dónde se encuentre el <b>"Número de comparendo".</b></p>
</div>
<%= simple_form_for :csv, url: process_infringements_path(@batch), method: :post, html: {class: "ui form attached fluid segment"} do |f| %>
<div class="field">
  <%= f.input :infringement_type, collection: %w(EXONERADOS SANCIONADOS\ EN\ AUDIENCIA RP RC CADUCIDAD AVISOS AUTOMÁTICOS REVOCATORIA NÚMERO\ DE\ RESOLUCIÓN), label: "Tipo de comparendo", include_blank: false, wrapper: false, input_html: { class: "ui dropdown" } %>
</div>
<div class="field">
  <%= f.input :infringement_number, collection: @columns, label: "Número de comparendo", include_blank: false, wrapper: false, input_html: { class: "ui dropdown" } %>
</div>
<div class="field">
  <%= f.input :infringement_date, collection: @columns, label: "Fecha de resolución", include_blank: false, wrapper: false, input_html: { class: "ui dropdown" } %>
</div>
<button type="submit" class="ui olive button">
  Porcesar importación
</button>
<% end %>

app/views/infringements/show.html.erb
<div class="ui equal width centered grid">
  <div class="column">
    <div class="ui center aligned basic segment">
      <h2>Estado de pago</h2>
      <p>
        <%= @infringement.active ? "PAGO" : "NO PAGO" %>
      </p>
      <h3>Número de comparendo</h3>
      <p>
        <%= @infringement.code %>
      </p>
      <h3>Estado</h3>
      <p>
        <%= @infringement.infringement_type %>
      </p>
      <h3>Estado anterior</h3>
      <p>
        <%= @infringement.o_infringement_type %>
      </p>
      <h3>Fecha de resolución</h3>
      <p> <%= h @infringement.date %> </p>
    </div>
  </div>
</div>

app/views/infringements/upload.html.erb
<%= render partial: "shareds/upload", locals: { path: transfer_infringements_path } %>