config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [] do
    collection do
      get :search
      post :find
      post :export
      post :exclude
    end
  end

  resources :data, only: [:index] do
    collection do
      post :join
    end
  end
  resources :batches, only: [:index, :show]
  resources :payments, only: [] do
    collection do
      get :upload
      post :transfer
      get "/:batch_id/columns" => "payments#column", as: "columns"
      post "/:batch_id/process" => "payments#process_batch", as: "process"
    end
  end
  resources :infringements, only: [:show] do
    collection do
      get :upload
      post :transfer
      get "/:batch_id/columns" => "infringements#column", as: "columns"
      post "/:batch_id/process" => "infringements#process_batch", as: "process"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Indicadores</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="ui container">
    <!-- Header -->
    <div class="ui secondary pointing menu">
      <%= link_to "Home", root_path, class: "#{["index"].include?(params[:action]) && params[:controller] == "home" ? "active" : ""} item" %>
      <%= link_to "Buscar #Comparendo", search_home_index_path, class: "#{(["search","find", "show"].include?(params[:action]) && ["home","infringements"].include?(params[:controller])) ? "active" : ""} item" %>
      <%= link_to "Importar Comparendos", upload_infringements_path, class: "#{["upload"].include?(params[:action]) && params[:controller] == "infringements" ? "active" : ""} item" %>
      <%= link_to "Importar Pagos", upload_payments_path, class: "#{params[:controller] == "payments" ? "active" : ""} item" %>
      <%= link_to "Cruzar pagos", data_path, class: "#{params[:controller] == "data" ? "active" : ""} item" %>
      <%= link_to "Importaciones", batches_path, class: "#{params[:controller] == "batches" ? "active" : ""} item" %>
      <%= link_to "Cruce", exclude_home_index_path(format: :xlsx), class: "item", method: :post %>
    </div>
    <!-- Messages -->
    <%= semantic_flash %>
    <!-- Content -->
    <%= yield %>
  </div>

</body>
</html>